import os from "os";
console.log(os.arch());
console.log(os.cpus());
console.log(os.homedir());
console.log(os.hostname());
console.log(os.platform());
console.log(os.release());
console.log(os.tmpdir());
console.log(os.type());
console.log(os.uptime());
